model:
  family: diffusion_encoder
  n_dims: 20
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 101
out_dir: ../models/decision_tree_encoder/535ed35c-08b5-420e-9373-e4c5cbffc8ad
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 100
      start: 5
    points:
      end: 41
      inc: 1
      interval: 100
      start: 10
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 1.0e-05
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: decision_tree
  task_kwargs: {}
  train_steps: 500001
wandb:
  enabled: true
  entity: jaredanjerry-southern-university-of-science-technology
  log_every_steps: 10
  name: decision_tree_encoder
  notes: Training
  project: icl-dllm
