model:
  family: diffusion_decoder
  n_dims: 20
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 101
out_dir: ../models/relu2nn_decoder/a1259393-e9ad-400c-800e-e0a85e73f72d
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 100
      start: 5
    points:
      end: 101
      inc: 5
      interval: 2000
      start: 26
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 1.0e-05
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: relu_2nn_regression
  task_kwargs:
    hidden_layer_size: 100
  train_steps: 500001
wandb:
  enabled: true
  entity: jaredanjerry-southern-university-of-science-technology
  log_every_steps: 10
  name: relu2nn_decoder
  notes: Training
  project: icl-dllm
